### ISSUE TITLE
Import OPML doesn't work

### ISSUE THREAD

**Issue by cearum** [michaelkremenetsky/Refeed#3]
- I exported from OPML file from TT-RSS. 
- I go to settings to import OMPL file
- I select the file and click import
- I get the below result with nothing imported
 
![image](https://github.com/michaelkremenetsky/Refeed/assets/33786368/d0472eaf-b5d3-4d02-9225-62c9379aaabc)

**Comment by michaelkremenetsky** [comment]
Would it be possible for you to send me your OPML file or a stripped down version of it? Can't really debug this without seeing the OPML file.

**Comment by cearum** [comment]
[opml_files.zip](https://github.com/michaelkremenetsky/Refeed/files/14462672/opml_files.zip)

I removed a few items, but made sure it still had issues. I also realized I can remove the ttrss settings, but still had issues so I included both. Github would let me upload .opml file so I had to zip it.

**Comment by michaelkremenetsky** [comment]
Ok, it should be fixed with https://github.com/michaelkremenetsky/Refeed/commit/73befcdae41b8551d957d77bb6c725c816d8c17f seems like ttrss was using the text attribute for the title instead of the title attribute. There might be a small visual glitch with the progress still but it should import the feeds correctly now.
